name: js
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56177
title: John Shin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6f6'
    - '#454545'
    - '#797979'
    - '#0a0a0a'
    - '#989898'
  brandStrength: 0.9686912472825497
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
