name: js
favicon: null
layout_spectrum: 0.45962209114804864
typography_spectrum: 0.3854731807950884
title: John Shin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6f6'
    - '#454545'
    - '#797979'
    - '#0a0a0a'
    - '#989898'
  brandStrength: 0.9686912472825497
  lightness: 0.44419420626945794
  saturation: 0.8853933203499764
  rhythmicContrast: 0.6399466749280691
purpose: []
